FROM meanmongo

# Set development environment as default
ENV NODE_ENV development

# Install MEAN.JS Prerequisites
# RUN npm install --quiet -g gulp bower yo mocha karma-cli pm2 && npm cache clean

# Copy project and install npm packages
RUN mkdir -p /opt/mean.js/public/lib
WORKDIR /opt/mean.js
COPY package.json /opt/mean.js/package.json
RUN npm install --quiet && npm cache clean
COPY . /opt/mean.js